version: "3.6"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APACHE_DOCUMENT_ROOT: /var/www/html/${PUBLIC_FOLDER}
    container_name: "${NAME}_web"
    environment:
      - NETTE_DEBUG=true
    volumes:
      - ../:/var/www/html/
    networks:
      - common_network
    ports:
      - ${PORT_WEB}:80

  mariadb:
    # Fucking slow first run (CREATING DB) YOU MUST WAIT 30min!!!
    image: mariadb:10.5
    container_name: "${NAME}_db"
    command:
      - "--character-set-serve=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"
    environment:
      MYSQL_DATABASE: apirest
      MYSQL_PASSWORD: caraculo
      MYSQL_ROOT_PASSWORD: caraculo
      MYSQL_USER: user
      #    ports:
      #      - 50136:3306
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - common_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "${NAME}_phpmyadmin"
    environment:
      PHPMYADMIN_HTTPS: "false"
      PMA_ARBITRARY: "1"
      PMA_HOST: mariadb
      PMA_PORT: "3306"
    ports:
      - ${PORT_PHPMYADMIN}:80
    networks:
      - common_network
    logging:
      driver: json-file

networks:
  common_network:
