version: '3.6'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${NAME}_web"
    environment:
      - NETTE_DEBUG=true
    volumes:
      - ../:/var/www/html/
    networks:
      - ${NAME}_net
    ports:
      - ${PORT_WEB}:80

  mariadb:
    # Slow first run (CREATING DB) YOU MUST WAIT!!!
    image: mariadb:10.5
    container_name: "${NAME}_db"
    command:
      - "--character-set-serve=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"
    environment:
      MYSQL_DATABASE: apirest
      MYSQL_PASSWORD: caraculo
      MYSQL_ROOT_PASSWORD: caraculo
      MYSQL_USER: user
      # Uncomment following 2 lines if you want to access mariadb from outside
      #    ports:
      #      - ${PORT_DB}:3306
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - ${NAME}_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "${NAME}_phpmyadmin"
    environment:
      PHPMYADMIN_HTTPS: 'false'
      PMA_ARBITRARY: '1'
      PMA_HOST: mariadb
      PMA_PORT: '3306'
    ports:
      - ${PORT_PHPMYADMIN}:80
    networks:
      - ${NAME}_net
    logging:
      driver: json-file

networks:
  apirest_net:
